GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmVyY2ViYWwiLCJpYXQiOjE1ODE2Nzg2ODh9.hJWTl7Z-anuBjR4UNVaDT9fgyHMseZTWlwnNpE-_o90
###
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "Bercebal"
}
###